name: Build Flutter APK

on:
  push:
    branches:
      - update-to-index-with-arabic-support   # أو غيّرها لفرعك

      

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'  # أو غيّرها لنسختك

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: |
        set +e  # ← تجاهل الأخطاء واجعل السكربت يكمل
        flutter build apk --release || true

    - name: Upload APK
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
